---

- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: 192.168.10.3

  tasks:

    - name: Add unit file for Puma
      ansible.builtin.copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
        mode: "0644"
      notify: Reload puma

    - name: Add config for DB connection
      ansible.builtin.template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
        owner: ubuntu
        group: ubuntu
        mode: "0664"

    - name: Enable puma
      ansible.builtin.systemd:
        name: puma
        enabled: true

  handlers:
    - name: Reload puma
      ansible.builtin.systemd:
        name: puma
        state: restarted
